### ISSUE TITLE
GPL Licensed component

### ISSUE THREAD

**Issue by bcssov** [erri120/GameFinder#75]
I understand your project is MIT license but a component that you're using is licensed under GPL, is this still valid for your own project?

https://www.nuget.org/packages/NexusMods.Paths/

**Comment by erri120** [comment]
Most of GPL is clear-cut when it comes to modifying the source code. However, "using" a GPL-licensed library has been a point of debate for a long time: https://en.wikipedia.org/wiki/GNU_General_Public_License#Linking_and_derived_works

You can dive into this rabbit hole, but there is no definitive answer. The "using" debate is also only relevant for direct dependencies, not transient ones. This means libraries and programs using GameFinder (MIT) aren't affected by the direct dependency NexusMods.Paths (GPL-3) since it's a transient dependency at the end:

```mermaid
flowchart TB
  A[NexusMods.Paths: GPL-3]
  B[GameFinder: MIT] --> A
  C[Consumer] --> B
```

As a consumer of GameFinder, you are only impacted by the MIT license. I'm the author of both GameFinder and co-author of NexusMods.Paths since I work at Nexus Mods.

**Comment by lostmsu** [comment]
@bcssov since you are a co-author of NexusMods.Paths, can you advocate the library to switch to LGPL to clear the "debate"?

**Comment by bcssov** [comment]
> @bcssov since you are a co-author of NexusMods.Paths, can you advocate the library to switch to LGPL to clear the "debate"?
> 
> AFAIK, transiency of the dependency is inconsequential: for all practical purposes I will have to distribute NexusMods.Paths with my software if I am to use GameFinder.
> 
> If LGPL change proves too hard, GameFinder could take the dependency out into an addon, and remove the dependency from the main lib.

I am sorry but I am not related to either project(s). I was in the same boat as you.

**Comment by lostmsu** [comment]
> I am sorry but I am not related to either project(s). I was in the same boat as you.

Sorry, mixed you up with @erri120
